[package]
name = "fractal-renderer-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "fractal-render"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
fractal-renderer-core = { path = "../renderer-core" }
fractal-renderer-workflow = { path = "../renderer-workflow" }
image.workspace = true
pollster.workspace = true
